name: 'Code Pipeline Build'
description: 'Run a mainframe build using Code Pipeline'
branding:
  icon: play
  color: orange
inputs:
  ces_url:
    description: 'The URL to send requests to.'
    required: true
  ces_token:
    description: 'The token to use when connecting to Code Pipeline through CES'
    required: false
  certificate:
    description: 'The certificate used when connecting to Code Pipeline through CES.'
    required: false
  srid:
    description: 'The ID for the instance of Code Pipeline to connect to'
    required: true
  runtime_configuration:
    description: 'The runtime configuration used when connecting to Code Pipeline'
    required: false
  task_id:
    description: 'The comma-separated list of task IDs for the tasks that need to be built'
    required: false
  build_automatically:
    description: 'The request parameters for the generate will come from JSON passed in this input. This option is only valid when used in combination with a Git to Code Pipeline Integration step'
    required: false
  change_type: 
    description: 'S for standard, I for incidental, or E for emergency. Default value of S'
    required: true
    default: 'S'
  execution_status:
    description: 'I for immediate execution or at start date/time, H to create request in hold'
    required: true
    default: 'I'
outputs:
  generate_failed_count:
    description: 'The number of tasks that failed to build'
  generate_success_count:
    description: 'The number of tasks that built successfully'
  has_failures:
    description: 'Whether there were any build failures'
  is_timed_out:
    description: 'Whether the build timed out'
  task_count:
    description: 'The total number of tasks a build was initiated against'
  set_id:
    description: 'The ID of the set that was used for processing'
  url:
    description: 'The URL that can be used to retrieve information about the set that was used for processing'
  output_json:
    description: 'the JSON output from build'
runs:
  using: 'node12'
  main: 'dist/index.js'
